import os
import uuid
import sys
import json
import subprocess
from pathlib import Path
from typing import Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from livekit.api import AccessToken, VideoGrants

from app.graph.pitch_analyzer.main import load_company_context, run_extraction

router = APIRouter()

# The agent writes the report here after every session
_REPORT_PATH = Path(os.getcwd()) / "app" / "graph" / "pitch_analyzer" / "session_report.json"

AGENT_ENV_KEYS = [
    "GROQ_API_KEY", "DEEPGRAM_API_KEY", "ELEVENLABS_API_KEY",
    "LIVEKIT_API_KEY", "LIVEKIT_API_SECRET", "LIVEKIT_URL",
]


@router.get("/env-check", summary="Check Required Env Vars are Set")
async def env_check():
    """
    Returns which required env vars are present vs missing.
    Never exposes actual values — only key names. Safe for production debugging.
    """
    present = [k for k in AGENT_ENV_KEYS if os.environ.get(k)]
    missing = [k for k in AGENT_ENV_KEYS if not os.environ.get(k)]
    return {
        "ok": len(missing) == 0,
        "present": present,
        "missing": missing,
        "cwd": os.getcwd(),
    }



@router.get("/report", summary="Fetch Latest Session Report")
async def get_session_report():
    """
    Returns the Investment Readiness Report generated by the AI agent
    at the end of the last pitch session (session_report.json).
    Returns 404 if no session has completed yet.
    """
    if not _REPORT_PATH.exists():
        raise HTTPException(status_code=404, detail="No session report found. Run a pitch session first.")
    try:
        data = json.loads(_REPORT_PATH.read_text(encoding="utf-8"))
        return JSONResponse(content=data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read report: {str(e)}")

import threading
import logging as _logging

worker_process = None
_worker_log: list[str] = []   # ring-buffer of last 200 lines for /worker-status tail
_LOG_MAX = 200


def _stream_output(proc: subprocess.Popen) -> None:
    """
    Reads the worker subprocess stdout line-by-line and:
      1. Forwards every line to the parent Python logger (appears in Azure log stream)
      2. Keeps the last _LOG_MAX lines in memory for diagnostics
    """
    try:
        for raw in proc.stdout:                       # type: ignore[union-attr]
            line = raw.rstrip("\n")
            _worker_log.append(line)
            if len(_worker_log) > _LOG_MAX:
                _worker_log.pop(0)
            _logging.info("[AGENT] %s", line)
    except Exception:
        pass


@router.post("/extract", summary="Run LLM Pre-flight Extraction")
def run_pitch_extraction():
    """
    Runs the LLM extraction pipeline separately from the worker.
    Call this when the user clicks on the pitchdeck, so it processes the documents
    in the background BEFORE they actually start the voice session.
    """
    try:
        docs = load_company_context()
        # Force skip=False so it guarantees the extraction runs and creates/updates the cache
        cheat_sheet, voice_prompt = run_extraction(docs, skip=False)
        return {"status": "success", "message": "Extraction finished and cache updated."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Extraction failed: {str(e)}")


@router.post("/start", summary="Start LiveKit AI Agent Worker")
async def start_agent_worker():
    global worker_process, _worker_log
    import asyncio as _asyncio

    # --- Already running? Return immediately ---
    if worker_process is not None and worker_process.poll() is None:
        return {"status": "already_running", "pid": worker_process.pid}

    script_path = os.path.join(os.getcwd(), "app", "graph", "pitch_analyzer", "main.py")
    if not os.path.exists(script_path):
        raise HTTPException(status_code=500, detail=f"Agent script not found at {script_path}")

    env = os.environ.copy()
    _worker_log.clear()

    # --- Verify env vars BEFORE spawning (surface the error clearly) ---
    required_keys = ["GROQ_API_KEY", "DEEPGRAM_API_KEY", "ELEVENLABS_API_KEY",
                     "LIVEKIT_API_KEY", "LIVEKIT_API_SECRET", "LIVEKIT_URL"]
    missing = [k for k in required_keys if not env.get(k)]
    if missing:
        raise HTTPException(
            status_code=500,
            detail=f"Cannot start agent worker — missing env vars: {', '.join(missing)}"
        )

    # --- Spawn subprocess with PIPE stdout so we can forward to Azure log stream ---
    _logging.info("[AGENT START] Spawning LiveKit agent worker from %s", script_path)
    worker_process = subprocess.Popen(
        [sys.executable, script_path, "dev", "--skip-extraction"],
        cwd=os.getcwd(),          # project root — .env and cache resolve here
        env=env,
        stdout=subprocess.PIPE,   # ← PIPE so we can read and forward to parent stdout
        stderr=subprocess.STDOUT, # merge stderr into stdout
        text=True,
        bufsize=1,                # line-buffered
    )

    # Spin up a daemon thread to forward subprocess logs to Azure's log stream
    t = threading.Thread(target=_stream_output, args=(worker_process,), daemon=True)
    t.start()

    # Give it 3 seconds to detect a crash-on-startup (missing keys, import error, etc.)
    await _asyncio.sleep(3)
    exit_code = worker_process.poll()
    if exit_code is not None:
        tail = "\n".join(_worker_log[-20:]) or "(no output captured)"
        raise HTTPException(
            status_code=500,
            detail=f"Agent worker crashed at startup (exit {exit_code}).\n\nLast output:\n{tail}"
        )

    _logging.info("[AGENT START] Worker is alive — pid=%s", worker_process.pid)
    return {"status": "started", "pid": worker_process.pid}


@router.get("/worker-status", summary="Check if AI Worker is Running")
async def get_worker_status():
    """Returns whether the Python AI worker subprocess is currently alive, plus log tail."""
    global worker_process, _worker_log
    if worker_process is None:
        return {"running": False, "reason": "never_started", "log_tail": []}
    code = worker_process.poll()
    tail = list(_worker_log[-30:])
    if code is None:
        return {"running": True, "pid": worker_process.pid, "log_tail": tail}
    return {"running": False, "reason": f"exited_with_code_{code}", "log_tail": tail}


class TokenRequest(BaseModel):
    participant_name: Optional[str] = "Founder"
    room_name: Optional[str] = None

@router.post("/token", summary="Generate LiveKit Token for Pitch Analyzer")
async def generate_pitch_analyzer_token(request: TokenRequest):
    api_key = os.getenv("LIVEKIT_API_KEY")
    api_secret = os.getenv("LIVEKIT_API_SECRET")

    if not api_key or not api_secret:
        raise HTTPException(status_code=500, detail="LIVEKIT_API_KEY missing")

    room_name = request.room_name or f"pitch-session-{uuid.uuid4().hex[:8]}"
    participant_identity = f"user_{uuid.uuid4().hex[:4]}"

    grant = VideoGrants(
        room=room_name,
        room_join=True,
        can_publish=True,
        can_publish_data=True,
        can_subscribe=True,
    )

    token = AccessToken(api_key=api_key, api_secret=api_secret).with_identity(participant_identity).with_name(request.participant_name).with_grants(grant)

    return {
        "access_token": token.to_jwt(),
        "room_name": room_name,
        "participant_identity": participant_identity
    }
