import os
import uuid
import sys
import json
import subprocess
from pathlib import Path
from typing import Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from livekit.api import AccessToken, VideoGrants

from app.graph.pitch_analyzer.main import load_company_context, run_extraction

router = APIRouter()

# The agent writes the report here after every session
_REPORT_PATH = Path(os.getcwd()) / "app" / "graph" / "pitch_analyzer" / "session_report.json"


@router.get("/report", summary="Fetch Latest Session Report")
async def get_session_report():
    """
    Returns the Investment Readiness Report generated by the AI agent
    at the end of the last pitch session (session_report.json).
    Returns 404 if no session has completed yet.
    """
    if not _REPORT_PATH.exists():
        raise HTTPException(status_code=404, detail="No session report found. Run a pitch session first.")
    try:
        data = json.loads(_REPORT_PATH.read_text(encoding="utf-8"))
        return JSONResponse(content=data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read report: {str(e)}")

worker_process = None

@router.post("/extract", summary="Run LLM Pre-flight Extraction")
def run_pitch_extraction():
    """
    Runs the LLM extraction pipeline separately from the worker.
    Call this when the user clicks on the pitchdeck, so it processes the documents
    in the background BEFORE they actually start the voice session.
    """
    try:
        
        # Load documents (currently hardcoded demo docs in main.py)
        docs = load_company_context()
        
        # Force skip=False so it guarantees the extraction runs and creates/updates the cache
        cheat_sheet, voice_prompt = run_extraction(docs, skip=False)
        
        return {"status": "success", "message": "Extraction finished and cache updated."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Extraction failed: {str(e)}")

@router.post("/start", summary="Start LiveKit AI Agent Worker")
async def start_agent_worker():
    global worker_process

    if worker_process is not None and worker_process.poll() is None:
        return {"status": "already_running", "pid": worker_process.pid}

    # The script lives under <project_root>/app/graph/pitch_analyzer/main.py
    # os.getcwd() is the FastAPI server root (project root), which is correct.
    script_path = os.path.join(os.getcwd(), "app", "graph", "pitch_analyzer", "main.py")
    if not os.path.exists(script_path):
        raise HTTPException(status_code=500, detail=f"Agent script not found at {script_path}")

    env = os.environ.copy()

    # Log goes to the project root (same cwd as FastAPI server)
    log_path = os.path.join(os.getcwd(), "agent_worker.log")
    log_file = open(log_path, "a", encoding="utf-8")

    # cwd = project root so that cheat_sheet_cache.json and .env resolve correctly
    worker_process = subprocess.Popen(
        [sys.executable, script_path, "dev", "--skip-extraction"],
        cwd=os.getcwd(),   # <-- project root, NOT the pitch_analyzer subfolder
        env=env,
        stdout=log_file,
        stderr=subprocess.STDOUT
    )

    import asyncio as _asyncio
    # Wait briefly to detect immediate crash (e.g., missing env vars → sys.exit(1))
    await _asyncio.sleep(2)
    exit_code = worker_process.poll()
    if exit_code is not None:
        # Read last lines of log for diagnosis
        try:
            with open(log_path, "r", encoding="utf-8") as f:
                tail = "".join(f.readlines()[-20:])
        except Exception:
            tail = "(log unavailable)"
        raise HTTPException(
            status_code=500,
            detail=f"Worker crashed immediately (exit code {exit_code}). Last log:\n{tail}"
        )

    return {"status": "started", "pid": worker_process.pid}


@router.get("/worker-status", summary="Check if AI Worker is Running")
async def get_worker_status():
    """Returns whether the Python AI worker subprocess is currently alive."""
    global worker_process
    if worker_process is None:
        return {"running": False, "reason": "never_started"}
    code = worker_process.poll()
    if code is None:
        return {"running": True, "pid": worker_process.pid}
    return {"running": False, "reason": f"exited_with_code_{code}"}


class TokenRequest(BaseModel):
    participant_name: Optional[str] = "Founder"
    room_name: Optional[str] = None

@router.post("/token", summary="Generate LiveKit Token for Pitch Analyzer")
async def generate_pitch_analyzer_token(request: TokenRequest):
    api_key = os.getenv("LIVEKIT_API_KEY")
    api_secret = os.getenv("LIVEKIT_API_SECRET")

    if not api_key or not api_secret:
        raise HTTPException(status_code=500, detail="LIVEKIT_API_KEY missing")

    room_name = request.room_name or f"pitch-session-{uuid.uuid4().hex[:8]}"
    participant_identity = f"user_{uuid.uuid4().hex[:4]}"

    grant = VideoGrants(
        room=room_name,
        room_join=True,
        can_publish=True,
        can_publish_data=True,
        can_subscribe=True,
    )

    token = AccessToken(api_key=api_key, api_secret=api_secret).with_identity(participant_identity).with_name(request.participant_name).with_grants(grant)

    return {
        "access_token": token.to_jwt(),
        "room_name": room_name,
        "participant_identity": participant_identity
    }
