import os

# Base output directory
OUTPUT_DIR = "data_output"

# LLM Configurations
DEFAULT_LLM_PROVIDER = "gemini"

# Temperatures
TEMPERATURE_GAP_ANALYZER = 0.3
TEMPERATURE_GENERATOR = 0.7
TEMPERATURE_BARRIER_EXTRACTION = 0.3
TEMPERATURE_WEAKNESS_ANALYSIS = 0.2
TEMPERATURE_TOWS_SYNTHESIS = 0.2

# Extraction Limits
TOP_COMPETITORS_LIMIT = 3
SNIPPETS_PER_COMPETITOR_LIMIT = 5
BARRIER_SNIPPETS_LIMIT = 15
WEAKNESS_SNIPPETS_LIMIT = 20

# Search Params
REVIEW_BASE_KEYWORDS = '"too expensive" OR "hard to use" OR "missing feature" OR "bad support" OR "alternative"'

# Weakness Thresholds
PAIN_SCORE_CRITICAL = 40
PAIN_SCORE_MODERATE = 65

SEARCH_VOLUME_LOW = 1000
SEARCH_VOLUME_MODERATE = 10000

CAC_VERY_HIGH = 500
CAC_HIGH = 150

LTV_CAC_POOR = 1.5
LTV_CAC_WEAK = 3.0

PAYBACK_PERIOD_DANGEROUS = 24
PAYBACK_PERIOD_LONG = 12

MARGIN_LOW = 30
MARGIN_MODERATE = 60

COMPETITOR_COUNT_SATURATED = 10
COMPETITOR_COUNT_COMPETITIVE = 5

MARKET_STRUCTURE_HIGH_RISK = ["Oligopoly/Monopoly", "Highly Fragmented/Red Ocean"]
MARKET_STRUCTURE_MODERATE_RISK_KEYWORD = "Competitive"
